

collections:
        contributions:
                output: true
defaults:
        - scope:
                path: ""
                type: contributions

          values:
                layout: default
